---
- name: Apply Security Policies to Systems
  hosts: all
  vars_files:
    - secrets.yml
  roles:
    - role: windows
      when: ansible_os_family == "Windows"
    - role: linux
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
    - role: macos
      when: ansible_os_family == "Darwin"
